version: "3.8"

services:
  # webserver service
  server:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: nginx-dp-container
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/nginx/certs:/etc/nginx/certs
    depends_on:
      - php
    networks:
      - dp-network
  # php language service
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: php-dp-container
    ports:
      - 9000:9000
    volumes:
      - ./:/var/www/html:delegated
    networks:
      - dp-network

networks:
  dp-network:
